[GSSOC '23] : Word Embedding Using Pytorch #356
The-Data-Alchemists-Manipal/MindWave pull request #360
Opened 2023-06-12 07:25 UTC by amankumar100

## Description
(This is a Python code for word embedding using Pytorch.)

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues or Pull Requests
(#356)
Solved

2023-06-12 16:55 UTC, khusheekapoor requested changes
Hi, please update the readme of the DL folder as well.

2023-06-13 12:06 UTC, amankumar100 commented
Since the code uses the concept of Deep Learning (DL) so I have made this contribution under DL folder so what I have to update or change in this DL folder?

2023-06-17 08:28 UTC, amankumar100 commented
Please approve this one.

2023-06-17 09:22 UTC, khusheekapoor requested changes
Hi, please link the notebook to the readme of the main ML directory, not the folder you have created inside of it :)

2025-07-04 08:44 UTC, closed without merging