License Plate Detection #353
The-Data-Alchemists-Manipal/MindWave pull request #397
Opened 2023-06-16 11:57 UTC by Tisha6661

It is an OpenCV based, license plate detection technique, that gives you the license plate number, image, and date & time.

![image](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/98682478/dfdadac1-2f04-44de-881b-8bbcb7b6d929)

![image](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/98682478/51828413-2bac-4c4a-b578-d1abc9cd9a22)

![image](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/98682478/e6386f6b-82e6-4069-9117-5641e5fccb50)

2023-06-17 10:19 UTC, khusheekapoor requested changes
Hi, please add this under the Image Processing directory.

2023-06-18 06:16 UTC, Tisha6661 commented
@khusheekapoor do i need to change the name of the folder only, from OpenCV Projects to Image Processing?

2023-06-23 07:47 UTC, Tisha6661 commented
I have made the changes long ago, please verify. @khusheekapoor

2023-06-26 17:03 UTC, khusheekapoor approved these changes

2023-06-26 17:04 UTC, merged