Real Logo Detection
The-Data-Alchemists-Manipal/MindWave pull request #546
Opened 2023-06-28 18:15 UTC by Shreyg-27

## Description
Under the machine learning directory, I have added the subdirectory - Real Logo Detection. It has the dataset, the README file, and the Model(SVM). I have also updated the README.md file in the machine learning subdirectory. 

## Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
Close #325

2023-06-28 18:15 UTC, Shreyg-27 commented
Hi @khusheekapoor! I have added the machine learning model. Hope it's fine. 
Thank you!

2023-06-29 15:42 UTC, khusheekapoor requested changes
Hi, I see changes in multiple readmes. Could you please check?

2023-07-01 17:02 UTC, Shreyg-27 commented
Hi @khusheekapoor! I have made the changes. 
The deep learning readme was updated earlier because I had made a contribution(Animal Species Classification). Right now for this issue, I have updated the Machine Learning README. I had uploaded an extra folder, so removed it. 
Thank you!

2023-07-03 17:25 UTC, khusheekapoor approved these changes

2023-07-03 17:26 UTC, merged